### ISSUE TITLE
RuntimeError: cuda runtime error (10) : invalid device ordinal

### ISSUE THREAD

**Issue by wyfeng1020** [NVIDIA/semantic-segmentation#10]
Hi authors, thanks for sharing your great work!

I encounter an error that needs your help. I have set up the environment according to your instructions, and simply want to run the code with `sh train_cityscapes.sh`.
However, the following error occurs:

`Total world size:  8
Total world size:  8
Total world size:  8
Total world size:  8
Total world size:  8
Total world size:  8
Total world size:  8
Total world size:  8
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/yufeng/anaconda2/envs/deeplab/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp:33
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/yufeng/anaconda2/envs/deeplab/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp:33
My Rank: 0
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/yufeng/anaconda2/envs/deeplab/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp:33
My Rank: 1
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/yufeng/anaconda2/envs/deeplab/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp:33
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/yufeng/anaconda2/envs/deeplab/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp:33
    torch.cuda.set_device(args.local_rank)
  File "/home/yufeng/anaconda2/envs/deeplab/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/cuda/Module.cpp:33`.

Currently, I'm using one single machine which has 4 gpus, and I only train with 2 gpus. I tried to set `CUDA_VISIBLE_DEVICES=0,1` , but it doesn't work.

I guess this problem is related to the distributed training process, which I'm not familiar with. What's the role of args.world_size and how to set it? Do I need to change the code from line 129 to 148 in train.py according to my setting?

Thanks!

**Comment by bryanyzhu** [comment]
Hi, `args.world_size` means how many GPUs you want to use for the experiment. Please change `--nproc_per_node=8` to `2` in [train_cityscapes.sh](https://github.com/NVIDIA/semantic-segmentation/blob/master/scripts/train_cityscapes.sh#L4) because you only want to use 2 GPUs in your machine. This should solve the problem. 

But if you only use 2 GPUs with a total batch size of 4, there is a chance that you got worse result because of BN. Even with `sync-bn` on, you need at least batch size of 8 (which means bs=4 per GPU card) to achieve similar result.

**Comment by wyfeng1020** [comment]
It works after changing the number. Thanks!
Since the total gpu memory is fixed,  increasing batch size means a decrease in the input scale (e.g., sett crop_size=512). Have you testified which one plays an essential role?

**Comment by bryanyzhu** [comment]
Compared to the baseline (batch size 16 and crop size 832), I have done experiments that:
1. batch size 8, crop size 832, it usually drop about 0.5 mIoU.
2. batch size 4, crop size 832,  it usually drop about 2.0 or more mIoU.
3. batch size 16, crop size 640, it usually drop about 0.5 mIoU. 
4. batch size 16, crop size 512, it usually drop 1.0~1.5 mIoU. 

Both of them are important. I suggest you use a batch size of 8, and try the largest crop size you can fit into your GPU memory.

**Comment by karansapra** [comment]
Also, I would suggest using fp16 using apex. This would help increase the bs. BS and crop size are a crucial aspect for semantic segmentation.

**Comment by wyfeng1020** [comment]
Got it. I'll take a try according to your advice.
Thanks so much for your kind reply!

**Comment by karansapra** [comment]
Please let me know if the issue persists or if we can close the issue :).

**Comment by wyfeng1020** [comment]
Yeah, sure. The problem has been solved. Thanks!
