### ISSUE TITLE
Error training on 8 GPUs

### ISSUE THREAD

**Issue by kwea123** [NVIDIA/semantic-segmentation#33]
I can successfully train on 4 GPUs, this is my first time using 8 GPUs, and after training for 18 epochs, it raises
```
RuntimeError: cuda runtime error (39) : uncorrectable ECC error encountered at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:265
terminate called without an active exception
```

**Comment by bryanyzhu** [comment]
Hi, I never encountered this error before. @karansapra Have you seen it? 

I searched online, and it seems it is hardware related issue. You can have a look at these posts.

https://github.com/JuliaGPU/CUDAdrv.jl/issues/106
https://stackoverflow.com/questions/11839555/cuda-uncorrectable-ecc-error-encountered
https://devtalk.nvidia.com/default/topic/670980/uncorrectable-ecc-error/

It seems that the solutions are:

1. reinstall cuda or 
2. perform training on each of the GPUs and try to find out which one may have defect

**Comment by kwea123** [comment]
Thank you.

**Comment by newtonysls** [comment]
Same issue happened in the same case. I also run my program in 8 GPUs. This error won't raise when I set the max length to 1536. Unfortunately, this error occurs when I set max length to 2048, which I can not believe it.

**Comment by newtonysls** [comment]
Damn, I thought this issue has been solved when I add os.environ['CUDA_LAUNCH_BLOCKING'] = '1' in my program. This stupid error happened again in the process of training.
